### ISSUE TITLE
文档能不能好好写下？

### ISSUE THREAD

**Issue by ChampionCatLi** [CCVideo/VOD_Android_DRM_SDK#1]
[VOD_Android_DRM_SDK](https://github.com/CCVideo/VOD_Android_DRM_SDK/wiki)
[VOD_Android_SDK](https://github.com/CCVideo/VOD_Android_SDK/wiki)
这两个文档内容一模一样？你这让开发者很头疼啊。糊弄人的是吧~好玩是吧~觉得我们发际线很高是吧~
DRM_SDK接入和普通的区别在哪里也不在文档里边注明。
那你丫的写这俩文档的意义何在啊？
真是气愤[○･｀Д´･ ○]，你们写的文档能不能自己look look 啊。
还有你们的DEMO，真是无力吐槽了。突然冒出来个方法，查阅API也不详细注明个别方法的用途与设计意义。
接入文档简陋无比,实际DEMO那叫一个臃肿，真是佛了。
从开发者角度来说，以后若有视频播放需求我绝不会推荐使用你们的服务！

**Comment by yych0807** [comment]
感谢您的评价和反馈，您的意见对我们很有价值。对因为我们的代码不完善给您带来的困扰，我们深表歉意。
我们的DEMO和SDK目前确实有很多不完善的地方，我们也意识到了。目前我们正在进行新版本的开发，请您期待我们后续发布的新版本。
关于两个版本选择的问题，如果您的视频有加密播放的需求，请选择DRM_SDK；如果不需要加密播放，请选择普通SDK。两个SDK的使用方式是完全一致的，对DRM和非DRM播放的不同处理逻辑封装在了SDK的内部。

**Comment by ChampionCatLi** [comment]
> 感谢您的评价和反馈，您的意见对我们很有价值。对因为我们的代码不完善给您带来的困扰，我们深表歉意。
> 我们的DEMO和SDK目前确实有很多不完善的地方，我们也意识到了。目前我们正在进行新版本的开发，请您期待我们后续发布的新版本。
> 关于两个版本选择的问题，如果您的视频有加密播放的需求，请选择DRM_SDK；如果不需要加密播放，请选择普通SDK。两个SDK的使用方式是完全一致的，对DRM和非DRM播放的不同处理逻辑封装在了SDK的内部。

真的是一样的吗？DRM播放方式难道不用启动DRM服务去解析吗？如果不启动该服务视频是无法播放的！虽然只是启动个服务的事，但是启不启动这个服务直接关系到视频能不能播放。
这么重要的事情你们DRM文档只字未提！
而且 在你们DEMO中启动DRM服务是放在Application，停止服务直接扔在了Appcalition中的 **onTerminate** 回调中，您们写DEMO这么不严谨吗？请您们点击 **onTerminate** 的源码查看下该方法的注释，只会在模拟器中回调，真机不会回调！
